name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: sw vers
      run: |
        sw_vers
    - name: system_profiler
      run: |
        system_profiler SPSoftwareDataType
    - name: pkgutil --pkgs
      run: |
        pkgutil --pkgs
    - name: pkgutil --help
      run: |
        pkgutil --help
    - name: bash --version
      run: |
        bash --version
        brew install bash
        chsh -s /usr/local/Cellar/bash/5.0.17/bin/bash
        bash --version
